In [1]:
import numpy as np
import pandas as pd

In [2]:
ml=np.arange(1,21).reshape(5,4)
ml

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [3]:
df = pd.DataFrame(ml,index=[1,2,3,4,5], columns=['W','X','Y','Z'])
df

W   X   Y   Z
1   1   2   3   4
2   5   6   7   8
3   9  10  11  12
4  13  14  15  16
5  17  18  19  20

In [4]:
df.loc[4]

W    13
X    14
Y    15
Z    16
Name: 4, dtype: int64

In [5]:
df.iloc[1]

W    5
X    6
Y    7
Z    8
Name: 2, dtype: int64

In [6]:
## Converting data into 'csv' format 
#df.to_csv('Test1.csv')

In [7]:
my_data = [10, 20, 30]
labels = ['a', 'b', 'c']
ndf = pd.Series(data = my_data, index = labels)
ndf

a    10
b    20
c    30
dtype: int64

In [8]:
df1 = pd.DataFrame(ml,['A', 'B', 'C', 'D','E'], ['W', 'X', 'Y', 'Z'])
df1

W   X   Y   Z
A   1   2   3   4
B   5   6   7   8
C   9  10  11  12
D  13  14  15  16
E  17  18  19  20

In [9]:
df.loc[1].unique()

array([1, 2, 3, 4])

In [10]:
df.iloc[1].unique()

array([5, 6, 7, 8])